[package]
authors = ["Xavier Lau <c.estlavie@icloud.com>"]
edition = "2018"
name    = "staking-ledger-checker"
version = "0.1.0"

[dependencies]
array-bytes = "1.3.3"
colored     = "2.0.0"
serde       = { version = "*", features = ["derive"] }
serde_json  = "1.0.64"
subcryptor  = "0.2.0"
